/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/device": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发起设备授权 */
        post: operations["createDeviceAuthorization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/device/{deviceCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 轮询设备授权 */
        get: operations["pollDeviceAuthorization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户 */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取我的在线 Skill */
        get: operations["listMySkills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 Tag 列表 */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取公开 Skill 列表 */
        get: operations["listSkills"];
        put?: never;
        /** 创建 Skill */
        post: operations["createSkill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skillId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取 Skill 详情
         * @description 归档 Skill 仅对其 Owner、协作者和管理员返回完整详情。
         */
        get: operations["getSkill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改平台展示信息 */
        patch: operations["updateSkillMetadata"];
        trace?: never;
    };
    "/api/skills/{skillId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取版本历史 */
        get: operations["listSkillVersions"];
        put?: never;
        /** 发布新版本 */
        post: operations["publishSkillVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skillId}/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取版本详情 */
        get: operations["getSkillVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skillId}/versions/{versionId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取版本文件树 */
        get: operations["listVersionFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skillId}/versions/{versionId}/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取文本文件内容 */
        get: operations["getVersionFileContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skillId}/versions/{versionId}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 撤回版本 */
        post: operations["withdrawSkillVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skillId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 归档 Skill */
        post: operations["archiveSkill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skillId}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 恢复 Skill */
        post: operations["restoreSkill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skillId}/installation-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询已安装 Skill 的在线状态 */
        get: operations["getInstallationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skillId}/ownership-transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发起所有权转移邀请 */
        post: operations["createOwnershipTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ownership-transfers/{transferId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 接受所有权转移 */
        post: operations["acceptOwnershipTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ownership-transfers/{transferId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 拒绝所有权转移 */
        post: operations["rejectOwnershipTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ownership-transfers/{transferId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消所有权转移 */
        post: operations["cancelOwnershipTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{skillId}/versions/{versionId}/download-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 获取版本下载凭证 */
        post: operations["createDownloadTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/installations/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 通过名称和内容哈希恢复平台关联 */
        post: operations["resolveInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/installations/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上报成功安装事件 */
        post: operations["createInstallationEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取通知 */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 全部标记已读 */
        post: operations["readAllNotifications"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notificationId}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 标记单条通知已读 */
        post: operations["readNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        ErrorBody: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            } | null;
        };
        User: {
            id: string;
            name: string;
            /** Format: uri */
            avatarUrl: string | null;
            departmentPath: string[];
            /** @enum {string} */
            status: "ACTIVE" | "DISABLED";
            /** @enum {string} */
            role: "USER" | "ADMIN";
            /** Format: date-time */
            syncedAt: string;
        };
        Tag: {
            id: string;
            name: string;
        };
        DerivedSource: {
            skillId: string;
            skillName: string;
            versionId: string;
            version: string;
            /** @enum {string} */
            status: "ACTIVE" | "ARCHIVED" | "NAME_CONFLICT";
            linkable: boolean;
        };
        SkillVersion: {
            id: string;
            skillId: string;
            version: string;
            /** @enum {string} */
            status: "PUBLISHED" | "WITHDRAWN";
            skillName: string;
            skillDescription: string;
            changelog: string;
            baseVersionId: string | null;
            packageSize: number;
            packageSha256: string;
            contentHash: string;
            uploadedBy: components["schemas"]["User"];
            /** Format: date-time */
            publishedAt: string;
            withdrawnBy: components["schemas"]["User"] | null;
            /** Format: date-time */
            withdrawnAt: string | null;
            withdrawalReason: string | null;
        };
        SkillVersionDetail: components["schemas"]["SkillVersion"] & {
            skillMd: string;
        };
        SkillSummary: {
            id: string;
            skillName: string;
            displayName: string;
            skillDescription: string;
            displayDescription: string;
            /** @enum {string} */
            status: "ACTIVE" | "ARCHIVED" | "NAME_CONFLICT";
            owner: components["schemas"]["User"];
            tags: components["schemas"]["Tag"][];
            currentVersion: components["schemas"]["SkillVersion"];
            installCount: number;
            derivedFrom: components["schemas"]["DerivedSource"] | null;
            updatedBy: components["schemas"]["User"];
            /** Format: date-time */
            archivedAt: string | null;
            archiveReason: string | null;
            nameConflictReason: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SkillDetail: components["schemas"]["SkillSummary"] & {
            collaborators: components["schemas"]["User"][];
            derivedChain: components["schemas"]["DerivedSource"][];
        };
        FileEntry: {
            path: string;
            /** @enum {string} */
            type: "FILE" | "DIRECTORY";
            size: number | null;
            sha256: string | null;
            previewable: boolean;
        };
        FileContent: {
            path: string;
            content: string;
            sha256: string;
        };
        DeviceAuthorization: {
            deviceCode: string;
            /** Format: uri */
            verificationUrl: string;
            expiresIn: number;
            interval: number;
        };
        AuthTokenResponse: {
            accessToken: string;
            /** @constant */
            tokenType: "Bearer";
            expiresIn: number;
            user: components["schemas"]["User"];
        };
        CreateSkillRequest: {
            /** Format: binary */
            file: string;
            displayName: string;
            displayDescription: string;
            tagIds?: string[];
            newTagNames?: string[];
            forkedFromSkillId?: string;
            forkedFromVersionId?: string;
            /** @default false */
            confirmDuplicateDisplayName: boolean;
        };
        PublishVersionRequest: {
            /** Format: binary */
            file: string;
            baseVersionId: string;
            version: string;
            changelog: string;
            displayName?: string;
            displayDescription?: string;
            tagIds?: string[];
            newTagNames?: string[];
            /** @default false */
            confirmDuplicateDisplayName: boolean;
        };
        UpdateSkillRequest: {
            displayName?: string;
            displayDescription?: string;
            tagIds?: string[];
            newTagNames?: string[];
            /** @default false */
            confirmDuplicateDisplayName: boolean;
        } | unknown | unknown | unknown | unknown;
        ReasonRequest: {
            reason: string;
        };
        CreateOwnershipTransferRequest: {
            targetUserId: string;
            reason?: string | null;
        };
        OwnershipTransfer: {
            id: string;
            skillId: string;
            fromOwner: components["schemas"]["User"];
            targetUser: components["schemas"]["User"];
            /** @enum {string} */
            status: "PENDING" | "ACCEPTED" | "REJECTED" | "CANCELED" | "EXPIRED";
            reason: string | null;
            createdBy: components["schemas"]["User"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            resolvedAt: string | null;
        };
        InstallationStatus: {
            skillId: string;
            /** @enum {string} */
            status: "ACTIVE" | "ARCHIVED" | "NAME_CONFLICT";
            /** Format: date-time */
            archivedAt: string | null;
            archiveReason: string | null;
            nameConflictReason: string | null;
            /** @enum {string|null} */
            versionStatus: "PUBLISHED" | "WITHDRAWN" | null;
            withdrawalReason: string | null;
            recommendedVersion: {
                id: string;
                version: string;
            } | null;
        };
        DownloadTicket: {
            /** Format: uri */
            url: string;
            /** Format: date-time */
            expiresAt: string;
            packageSha256: string;
            contentHash: string;
        };
        ResolveInstallationRequest: {
            skillName: string;
            contentHash: string;
        };
        InstallationResolution: {
            matched: boolean;
            skillId: string | null;
            versionId: string | null;
            /** @enum {string|null} */
            status: "ACTIVE" | "ARCHIVED" | "NAME_CONFLICT" | null;
            /** Format: date-time */
            archivedAt: string | null;
            archiveReason: string | null;
        };
        InstallationEventRequest: {
            eventId: string;
            skillId: string;
            versionId: string;
            /** Format: date-time */
            installedAt: string;
        };
        Notification: {
            id: string;
            /** @enum {string} */
            type: "VERSION_PUBLISHED" | "METADATA_UPDATED" | "OWNERSHIP_TRANSFER" | "SKILL_STATUS_CHANGED";
            title: string;
            body: string;
            skillId: string | null;
            /** Format: date-time */
            readAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        SkillPage: {
            items: components["schemas"]["SkillSummary"][];
            page: number;
            pageSize: number;
            total: number;
        };
        VersionPage: {
            items: components["schemas"]["SkillVersion"][];
            page: number;
            pageSize: number;
            total: number;
        };
        NotificationPage: {
            items: components["schemas"]["Notification"][];
            page: number;
            pageSize: number;
            total: number;
            unreadCount: number;
        };
    };
    responses: {
        /** @description 请求失败 */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        DeviceCode: string;
        SkillId: string;
        VersionId: string;
        TransferId: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createDeviceAuthorization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 授权会话已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceAuthorization"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    pollDeviceAuthorization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceCode: components["parameters"]["DeviceCode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 授权成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description 等待用户完成授权 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "PENDING";
                    };
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listMySkills: {
        parameters: {
            query: {
                relation: "OWNED" | "COLLABORATED" | "ARCHIVED";
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skill 分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillPage"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listTags: {
        parameters: {
            query?: {
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag 列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listSkills: {
        parameters: {
            query?: {
                query?: string;
                tagId?: string;
                sort?: "UPDATED_DESC" | "CREATED_DESC" | "INSTALLS_DESC";
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skill 分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillPage"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createSkill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateSkillRequest"];
            };
        };
        responses: {
            /** @description Skill 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skill 详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    updateSkillMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSkillRequest"];
            };
        };
        responses: {
            /** @description Skill 已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listSkillVersions: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionPage"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    publishSkillVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["PublishVersionRequest"];
            };
        };
        responses: {
            /** @description 新版本已发布 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getSkillVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillVersionDetail"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listVersionFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文件清单 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileEntry"][];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getVersionFileContent: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 文本文件内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileContent"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    withdrawSkillVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description 版本已撤回 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillVersion"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    archiveSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description Skill 已归档 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    restoreSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description Skill 已恢复 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    getInstallationStatus: {
        parameters: {
            query?: {
                /** @description 本地安装凭证记录的版本 ID，用于判断该版本是否已撤回。 */
                versionId?: string;
            };
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 最小在线状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallationStatus"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createOwnershipTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOwnershipTransferRequest"];
            };
        };
        responses: {
            /** @description 邀请已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipTransfer"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    acceptOwnershipTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transferId: components["parameters"]["TransferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已接受 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipTransfer"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    rejectOwnershipTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transferId: components["parameters"]["TransferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已拒绝 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipTransfer"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    cancelOwnershipTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transferId: components["parameters"]["TransferId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已取消 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OwnershipTransfer"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createDownloadTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 下载凭证 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadTicket"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    resolveInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveInstallationRequest"];
            };
        };
        responses: {
            /** @description 匹配结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallationResolution"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    createInstallationEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallationEventRequest"];
            };
        };
        responses: {
            /** @description 已记录或幂等接受 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                unreadOnly?: boolean;
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 通知分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationPage"];
                };
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    readAllNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已全部标记已读 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
    readNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notificationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 已标记已读 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["ErrorResponse"];
        };
    };
}
