/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/device/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发起设备授权 */
        post: operations["startDeviceAuthorization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/device/poll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 轮询设备授权结果 */
        get: operations["pollDeviceAuthorization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户 */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 Tag 列表 */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 Skill 列表 */
        get: operations["listSkills"];
        put?: never;
        /**
         * 创建 Skill
         * @description 客户端可先在本地解析 ZIP 用于预览；发布时一次性提交原始 ZIP 和平台信息，服务端重新校验包内容。
         */
        post: operations["createSkill"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{skillId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        /** 获取 Skill 详情 */
        get: operations["getSkill"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 修改 Skill 平台信息
         * @description 只有 Skill 原上传者可以修改展示名称、展示简介和 Tag；成功后不创建 SkillVersion。
         */
        patch: operations["updateSkillMetadata"];
        trace?: never;
    };
    "/skills/{skillId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        /** 获取版本历史 */
        get: operations["listSkillVersions"];
        put?: never;
        /**
         * 发布新版本
         * @description 一次性提交原始 ZIP 和版本信息，服务端重新校验包内容及 Skill 名称。
         */
        post: operations["createSkillVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{skillId}/versions/{versionId}/files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        /** 获取指定版本文件树 */
        get: operations["listSkillVersionFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{skillId}/versions/{versionId}/files/content": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        /** 获取指定文本文件内容 */
        get: operations["getSkillVersionFileContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{skillId}/versions/{versionId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        /** 获取指定版本下载凭证 */
        get: operations["getSkillVersionDownload"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/{skillId}/versions/{versionId}/install-events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上报成功安装 */
        post: operations["recordSkillInstallation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Format: uuid */
        Uuid: string;
        /** Format: date-time */
        DateTime: string;
        /** @example 1.2.0 */
        SemVer: string;
        Sha256: string;
        ApiError: {
            /** @enum {string} */
            error: "INVALID_REQUEST" | "INVALID_SKILL_PACKAGE" | "PACKAGE_TOO_LARGE" | "INVALID_SEMVER" | "UNAUTHENTICATED" | "USER_DISABLED" | "NOT_SKILL_OWNER" | "SKILL_NOT_FOUND" | "VERSION_NOT_FOUND" | "FILE_NOT_FOUND" | "FILE_PREVIEW_UNAVAILABLE" | "DUPLICATE_SKILL_NAME" | "SKILL_NAME_MISMATCH" | "VERSION_ALREADY_EXISTS" | "VERSION_NOT_GREATER" | "DOWNLOAD_UNAVAILABLE";
            message: string;
            details?: {
                [key: string]: unknown;
            };
            requestId?: string;
        };
        User: {
            id: components["schemas"]["Uuid"];
            name: string;
            /** Format: email */
            email: string | null;
            /** Format: uri */
            avatarUrl: string | null;
            /** @description 从上级部门到直接所属部门的名称路径，无法获取时为空数组。 */
            departmentPath: string[];
            /** @enum {string} */
            status: "ACTIVE" | "DISABLED";
        };
        Tag: {
            id: components["schemas"]["Uuid"];
            name: string;
        };
        SkillVersionSummary: {
            id: components["schemas"]["Uuid"];
            version: components["schemas"]["SemVer"];
            skillName: string;
            skillDescription: string;
            packageSize: number;
            publishedAt: components["schemas"]["DateTime"];
            uploadedBy: components["schemas"]["User"];
        };
        SkillVersion: components["schemas"]["SkillVersionSummary"] & {
            changelog: string | null;
            packageSha256: components["schemas"]["Sha256"];
            contentHash: components["schemas"]["Sha256"];
            skillMd: string;
        };
        SkillFileEntry: {
            path: string;
            /** @enum {string} */
            type: "FILE" | "DIRECTORY";
            size: number | null;
            mediaType: string | null;
            previewable: boolean;
        };
        SkillFileListResponse: {
            items: components["schemas"]["SkillFileEntry"][];
        };
        SkillFileContent: {
            path: string;
            mediaType: string;
            /** @constant */
            encoding: "UTF-8";
            size: number;
            content: string;
        };
        SkillSummary: {
            id: components["schemas"]["Uuid"];
            skillName: string;
            displayName: string;
            skillDescription: string;
            displayDescription: string;
            tags: components["schemas"]["Tag"][];
            latestVersion: components["schemas"]["SkillVersionSummary"];
            uploadedBy: components["schemas"]["User"];
            updatedBy: components["schemas"]["User"];
            installCount: number;
            createdAt: components["schemas"]["DateTime"];
            updatedAt: components["schemas"]["DateTime"];
        };
        SkillDetail: components["schemas"]["SkillSummary"] & {
            latestVersion: components["schemas"]["SkillVersion"];
        };
        Pagination: {
            total: number;
            page: number;
            pageSize: number;
        };
        SkillListResponse: components["schemas"]["Pagination"] & {
            items: components["schemas"]["SkillSummary"][];
        };
        SkillVersionListResponse: components["schemas"]["Pagination"] & {
            items: components["schemas"]["SkillVersion"][];
        };
        TagListResponse: {
            items: components["schemas"]["Tag"][];
        };
        DeviceAuthStartRequest: {
            clientName?: string;
            deviceName?: string;
            /** @enum {string} */
            platform?: "windows" | "macos" | "linux";
        };
        DeviceAuthStartResponse: {
            deviceCode: string;
            userCode: string;
            /** Format: uri */
            verificationUrl: string;
            expiresAt: components["schemas"]["DateTime"];
            pollInterval: number;
        };
        DeviceAuthPendingResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "DeviceAuthPendingResponse";
            pollInterval: number;
        };
        DeviceAuthAuthorizedResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "DeviceAuthAuthorizedResponse";
            user: components["schemas"]["User"];
            token: string;
            /** Format: date-time */
            expiresAt: string | null;
        };
        DeviceAuthTerminalResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "DeviceAuthTerminalResponse";
        };
        CurrentUserResponse: {
            user: components["schemas"]["User"];
            scopes: string[];
        };
        CreateSkillRequest: {
            /**
             * Format: binary
             * @description 最大 50 MB 的原始 Skill ZIP
             */
            file: string;
            displayName: string;
            displayDescription: string;
            tags: components["schemas"]["TagAssignmentInput"];
            version: components["schemas"]["SemVer"];
            changelog?: string;
        };
        CreateSkillVersionRequest: {
            /**
             * Format: binary
             * @description 最大 50 MB 的原始 Skill ZIP
             */
            file: string;
            version: components["schemas"]["SemVer"];
            changelog: string;
        };
        UpdateSkillMetadataRequest: {
            displayName?: string;
            displayDescription?: string;
            tags?: components["schemas"]["TagAssignmentInput"];
        };
        /** @description tagIds 与 newTagNames 合并、规范化和去重后最多 5 个 Tag。 */
        TagAssignmentInput: {
            tagIds: components["schemas"]["Uuid"][];
            newTagNames: string[];
        };
        DownloadTicket: {
            /** Format: uri */
            url: string;
            expiresAt: components["schemas"]["DateTime"];
            packageSize: number;
            packageSha256: components["schemas"]["Sha256"];
            contentHash: components["schemas"]["Sha256"];
        };
        InstallationEventRequest: {
            eventId: components["schemas"]["Uuid"];
            deviceId: string;
            /** @enum {string} */
            platform: "windows" | "macos" | "linux";
            clientVersion: components["schemas"]["SemVer"];
            installedAt: components["schemas"]["DateTime"];
        };
        InstallationEventResponse: {
            recorded: boolean;
            installCount: number;
        };
    };
    responses: {
        /** @description 请求参数或业务校验失败 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 未提供有效访问令牌 */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 当前用户被停用或无权执行操作 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 请求的资源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 资源身份、Skill 名称或版本发生冲突 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 文件类型不支持文本预览 */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description 下载服务暂时不可用 */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        SkillId: string;
        VersionId: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    startDeviceAuthorization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeviceAuthStartRequest"];
            };
        };
        responses: {
            /** @description 授权会话已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceAuthStartResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    pollDeviceAuthorization: {
        parameters: {
            query: {
                deviceCode: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前授权状态 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceAuthPendingResponse"] | components["schemas"]["DeviceAuthAuthorizedResponse"] | components["schemas"]["DeviceAuthTerminalResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 当前用户和权限范围 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listTags: {
        parameters: {
            query?: {
                /** @description 按 Tag 名称模糊搜索 */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tag 列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listSkills: {
        parameters: {
            query?: {
                /** @description 搜索 Skill 名称、展示名称、Skill 描述、展示简介和 Tag */
                q?: string;
                /** @description Tag UUID */
                tagId?: components["schemas"]["Uuid"];
                /** @description created 按创建时间，updated 按最新版本发布时间，popular 按安装次数倒序。 */
                sort?: "created" | "updated" | "popular";
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skill 分页列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    createSkill: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateSkillRequest"];
            };
        };
        responses: {
            /** @description Skill 已创建 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getSkill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Skill 详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateSkillMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSkillMetadataRequest"];
            };
        };
        responses: {
            /** @description 平台信息已更新 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listSkillVersions: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 按 SemVer 从高到低排列的版本列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillVersionListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    createSkillVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateSkillVersionRequest"];
            };
        };
        responses: {
            /** @description 新版本已发布 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listSkillVersionFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 规范化并按目录优先排序的文件条目 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillFileListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSkillVersionFileContent: {
        parameters: {
            query: {
                /** @description 文件树接口返回的规范化相对路径 */
                path: string;
            };
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UTF-8 文本文件内容 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillFileContent"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            415: components["responses"]["UnsupportedMediaType"];
        };
    };
    getSkillVersionDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 临时下载地址和校验信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadTicket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    recordSkillInstallation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                skillId: components["parameters"]["SkillId"];
                versionId: components["parameters"]["VersionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallationEventRequest"];
            };
        };
        responses: {
            /** @description 幂等安装事件处理结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallationEventResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
}
